name: lint
on:
  workflow_dispatch:
  pull_request:
    # Sequence of patterns matched against refs/heads
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 18
        cache: maven
        distribution: 'adopt'

    - name: lint with Maven
      run: mvn -f ./pom.xml clean site
    - uses: Juuxel/publish-checkstyle-report@v1
      with:
        reports: |
          **/scalastyle-output.xml

