name:  DLAPI Production Test

on:
  workflow_dispatch:
  schedule:
      - cron: '0 17 * * *'
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: maven
        distribution: 'adopt'

    - name: Test with Maven
      env:
        API_TOKEN_GLOBAL_OPSGENIE: ${{ secrets.API_TOKEN_GLOBAL_OPSGENIE }}
      run: mvn -f ./pom.xml clean install -DsuiteXmlFile=DLAPI_Test.xml

    - name: Slack Notification       
      uses: 8398a7/action-slack@v3
      with:
       channel : cre_automated_testing
       status: ${{ job.status }}
       fields: workflow,job,commit,repo,ref,author,took
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      if: always()
