name: cre-propDetail-perf-test

on: 
  schedule:
      - cron: '0 12 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        cache: maven
        distribution: 'adopt'
        

    - name: Adding secret
      run: |
          printf ${{ secrets.API_TOKEN_GLOBAL_OPSGENIE }} >> Config/CONFIG.properties
    - name: Test with Maven
      env:
        API_TOKEN_GLOBAL_OPSGENIE: ${{ secrets.API_TOKEN_GLOBAL_OPSGENIE }}
      run: mvn -f ./pom.xml clean install -DsuiteXmlFile=propDetailTimeLog.xml -Denvironment=Production



    # - name: Slack Notification       
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     channel: cre_automated_testing
    #     status: ${{ job.status }}
    #     fields: workflow,job,commit,repo,ref,author,took
    #     custom_payload: |
    #       {
    #         attachments: [{
    #           color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
    #           text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
    #         }]
    #       }
    #   env:
    #      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    #   if: always()
